version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/travis"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: responses
    versions:
    - 0.12.1
    - 0.13.0
    - 0.13.1
    - 0.13.2
  - dependency-name: lxml
    versions:
    - 4.6.2
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
